"""
Sound Change parser.

Note that, as described in the `README.md` file of this directory, the
parsers generated by 竜 TatSu are currently failing. As we need to
operate on the semantics nonetheless, this class load and compiles the
grammar dinamically on the first call.
"""

# Import Python standard libraries
from pathlib import Path

# Import 3rd party libraries
import tatsu

# TODO: compile a prettified grammar for saving some time on loading?
# TODO: check about color and trace options for parsing
# TODO: should memoize? tatsu should already be memoizing enough

class Parser:
    # Holds the grammar, loaded dinamically on first call
    _parser = None

    def __init__(self):
        pass

    def __call__(self, text, start="start"):
        # Load and compile the grammar if necessary
        if not self._parser:
            self._load_grammar()

        return self._parser.parse(text, start=start)

    # TODO: add logging
    # TODO: use pathlib
    def _load_grammar(self):
        """
        Internal function for loading and compiling a 竜 TatSu grammar.
        """

        grammar_path = Path(__file__).parent /  "grammar.peg"
        with open(grammar_path.as_posix()) as grammar:
            self._parser = tatsu.compile(grammar.read())
